import { createClient } from '@supabase/supabase-js';

// --- SUPABASE CONFIGURATION ---
// Replace the strings below with your actual Supabase project details.
// You can find these in your Supabase Dashboard under Settings > API.
const SUPABASE_URL = process.env['SUPABASE_URL'] || 'https://rchvhflfktrkruzrxkik.supabase.co';
const SUPABASE_KEY = process.env['SUPABASE_KEY'] || 'sb_secret_sW5NdRBLNNRWeY9y1FAGaA_tNgWf0JF';

export const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

/**
 * Note: Table initialization is now handled manually via the Supabase SQL Editor.
 * Please run the following SQL in your Supabase dashboard to set up the table:
 * 
 * CREATE TABLE players (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   name TEXT UNIQUE NOT NULL,
 *   wins INTEGER DEFAULT 0,
 *   goals INTEGER DEFAULT 0,
 *   assists INTEGER DEFAULT 0,
 *   rank TEXT DEFAULT 'Unranked',
 *   elo INTEGER DEFAULT 1000,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 */

export async function initDatabase() {
  console.log("Supabase client initialized.");
  // Verification check: try to fetch one row (optional)
  const { data, error } = await supabase.from('players').select('id').limit(1);
  if (error) {
    console.error("Error connecting to Supabase 'players' table:", error.message);
    console.log("Please ensure you have created the 'players' table in your Supabase SQL Editor.");
  } else {
    console.log("Successfully connected to Supabase 'players' table.");
  }
}
